### ISSUE TITLE
Created a basic shortcode based on this example, but doesn't save.

### ISSUE THREAD

**Issue by bowenac** [Theme-Fusion/Fusion-Builder-Sample-Add-On#1]
When I update a page that I have used a custom element I just created based on this example, the shortcode is not saving.

I can add the custom element, fill out the fields, click save, it inserts it into fusion builder. If I click on use default editor, I can see the shortcode with all of the correct values. When I click update, it reloads the page without this custom element.

Any ideas?

**Comment by bowenac** [comment]
It seems the problem is when the page loads using fusion builder. If I add the custom element, then click on default editor, update the page, it will then reload the page using the default editor and shows my custom element shortcode. If I click on fusion builder, it removes my custom shortcode/element, if I save while on fusion builder, it doesn't save the shortcode.

**Comment by lukeabeck** [comment]
Thanks for posting.

@Theme-Fusion/developers will reply here soon

**Comment by yawalkar** [comment]
Hey @bowenac,

Can you please try naming your shortcode with **fusion_** like **fusion_your_shortcode**

Let me know if that works.

**Comment by yawalkar** [comment]
Currently, you need to prepend the shortcode with **_fusion__** so it will be easy for FB to identify that its a part of elements. I have updated readme with the instructions to avoid future issues.

**Comment by bowenac** [comment]
Thanks, that fixed it!

**Comment by yawalkar** [comment]
Glad to know that fixed. We have also improved the FB API so it will also accept any shortcodes mapping. This change will be live with the next release of FB.
