### ISSUE TITLE
Adding a Custom Container

### ISSUE THREAD

**Issue by dloewen** [Theme-Fusion/Fusion-Builder-Sample-Add-On#10]
I'd like to add a custom container using the same format as a regular container with a single column. The difference is it would have custom settings, and when displaying on the front end, would customize the HTML output (wrapping tags around each element & the whole container). Is this customizability supported by Fusion Builder? If so, any hints on how this could be accomplished would be much appreciated.

**Comment by yawalkar** [comment]
Hi,

Currently this isn't possible with Fusion Builder, however, you can add a class name to the container and write a custom function that will check for that class name and then runs on the content inside that container and apply the wrapping tags logic on each element inside that container.

I hope this will help you.
