### ISSUE TITLE
Feature request: Dynamic FB elements & hook locations

### ISSUE THREAD

**Issue by Marcoevich** [Theme-Fusion/Fusion-Builder-Sample-Add-On#11]
Hi Theme-Fusion devs,

I'll add my questions here, per request. 

I’m working on a site with custom post types now. I create an archive page, which will display it’s dynamic content in fusion builder elements, because Fusion Builder is excellent for designing website pages.
 
I’m doing this by pre-creating the page in WP, and then copy relevant code into the php file, where I add php code into the elements. Like this: 
![image](https://cloud.githubusercontent.com/assets/1243033/23363313/5f6f2d56-fcfa-11e6-81e9-7a63be664fa1.png)

But isn’t there an easier way to do that? Do you have any plans to display FB elements via php shortcodes?
 
See for example the putRevSlider shortcode here: 
 
![image](https://cloud.githubusercontent.com/assets/1243033/23363356/93ae1c9e-fcfa-11e6-9fed-a9ea07f69ba9.png)

We could create a shortcode like fusion_column_1_3(arguments)

Then add any customization options you want with arguments, like in the real shortcode.

If that is not possible, then could you make something to display FB elements on hook locations? Then I can save a particular element in the library, and insert it in the footer, or header, or wherever I want with my own hooks.

This will extend the usability of fusion builder, allowing it to create custom dynamic content.

**Comment by Marcoevich** [comment]
Hello Theme-Fusion devs,

I hope someone has time to answer my question? :)

**Comment by mikka23** [comment]
Yo Rick, you should be able to use https://developer.wordpress.org/reference/functions/do_shortcode/

For example if you check the fusion-user-login we use that to incorporate the alert shortcode within its contents.  So you can use that to add the markup for a column (just add regular shortcode content)

**Comment by yawalkar** [comment]
Closing this for now, as there's nothing to do with the Fusion Builder.
