### ISSUE TITLE
Load More button stopped working in Avada 5.1.6

### ISSUE THREAD

**Issue by ghost** [Theme-Fusion/Fusion-Builder-Sample-Add-On#15]
H!i After I have upgraded to Avada 5.1.6 from 5.1.1 Load More button of my CPT shorcodes add-on stopped working. Can you please advise what you have changed and where.

**Comment by lukeabeck** [comment]
@maximus80 @yawalkar @ilicfilip  ... isn't this one of the items we had fixed for the next update?

It's ringing a bell, @ilicfilip was the one to take care of it I believe, I just can't find the ticket #

**Comment by lukeabeck** [comment]
Found it: https://github.com/Theme-Fusion/Fusion-Builder/issues/821 ... I don't think this is related.

@waubau when you say stopped working, what exactly happens? Does the button not load anything? Or does the button still show after all posts have loaded?

**Comment by ghost** [comment]
When I click the button nothing happens. My add-on was based on your Blog shortcode 5.1.0 so the question may sound like what you have changed in your Blog shortcode regarding Load more and infinite scroll in the last few minor versions.  I guess it is something related to isotope. I don't test every minor update hoping that there will be no breaking changes but pagination other then classical one stopped working.

**Comment by yawalkar** [comment]
@waubau Can you please provide your add-on, so that we can check whats wrong? If you have used the blog shortcode structure in your add-on, you might need to update it, as we have changed some classes.

Can you please check if our blog shortcode / blog archive page works with all the pagination for you? If that works, then please check the latest shortcode classes and try changing your add-on code accordingly.

**Comment by ghost** [comment]
@yawalkar 
I have added the shortcode file. If you can quickly see what needs to be changed please let me know. 

[fusion-blog-cpt.zip](https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/files/977008/fusion-blog-cpt.zip)

**Comment by ghost** [comment]
I have modified it, so now it works. I am not sure if it will work with previous 5.1.x versions. Since you are building a platform you should keep an eye on backward compatibility of your minor upgrades.

**Comment by lukeabeck** [comment]
> Since you are building a platform you should keep an eye on backward compatibility of your minor upgrades.

Of course, we do as much as possible.
