### ISSUE TITLE
Descriptive Tutorial

### ISSUE THREAD

**Issue by tyler-canton** [Theme-Fusion/Fusion-Builder-Sample-Add-On#19]
I tried creating a custom addon by copying a text component however its just not working for me. Can someone help me with initial steps...

**Comment by mikka23** [comment]
Hi @tyler-canton 

I would recommend starting with the sample add-on and combine that with our documentation on the API.  That way you can see a working example and cross-match the various parts of the code with the descriptions in the documentation.

API documentation is here - https://theme-fusion.com/support/documentation/fusion-builder-api-documentation/
Sample add-on can be download from this Git repo.  Move it to the plugins folders on your set-up and activate.

A few things to note:

- Once you have installed and activated the sample add-on plugin you may also need to go to Fusion Builder > Settings and check the new element to see it in the builder - Quotes Rotator ( Sample Addon )

- The Sample Add-on is a parent + child element, which is a bit more complex than a simple element.

- They key code in the Same Add-on to check is this - https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/master/fusion-builder-sample-add-on.php#L106-L122  That is the actual output that will be displayed on the page, for the shortcode defined here - https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/master/fusion-builder-sample-add-on.php#L62  The basic idea is you need to add some options to set the parameters, then use these parameters in your render.


If you are still having some difficulties getting started, if you can provide a little more information on what you would like help with I should be able to add some more specific instructions and a more streamlined sample for you (the sample add-on is quite complex in comparison to the basic requirements for a simple new element).

**Comment by tyler-canton** [comment]
I'm a little confused, the Table addon is a custom addon. Yet it is written completely different from the sample add on.



    <?php

     if ( fusion_is_element_enabled( 'fusion_hero' ) ) {

	if ( ! class_exists( 'FusionSC_FusionHero' ) ) {
		/**
		 * Shortcode class.
		 *
		 * @package fusion-builder
		 * @since 1.0
		 */
		class FusionSC_FusionHero extends Fusion_Element {

			/**
			 * An array of the shortcode arguments.
			 *
			 * @access protected
			 * @since 1.0
			 * @var array
			 */
			protected $args;

			/**
			 * Constructor.
			 *
			 * @access public
			 * @since 1.0
			 */
			public function __construct() {
				parent::__construct();
				add_shortcode( 'fusion_hero', array( $this, 'render' ) );

				add_filter( 'fusion_hero_content', 'shortcode_unautop' );
				add_filter( 'fusion_hero_content', 'do_shortcode' );
			}

			/**
			 * Render the shortcode
			 *
			 * @access public
			 * @since 1.0
			 * @param  array  $args    Shortcode parameters.
			 * @param  string $content Content between shortcode.
			 * @return string          HTML output.
			 */
			public function render( $args, $content = '' ) {
				return apply_filters( 'fusion_hero_content', fusion_builder_fix_shortcodes( $content )
				);
			}
		}
	}

	new FusionSC_FusionHero();

    }

    /**
     * Map shortcode to Fusion Builder.
    */
    function fusion_element_hero() {
	fusion_builder_map(
		array(
			'name'             => __( 'Hero Component', 'fusion-builder' ),
			'shortcode'        => 'fusion_hero',
			'icon'             => 'fusiona-table',
			'allow_generator'  => true,
			'admin_enqueue_js' => FUSION_BUILDER_PLUGIN_URL . 'shortcodes/js/fusion-table.js',
			'params'           => array(
				array(
					'type'        => 'select',
					'heading'     => esc_attr__( 'Type', 'fusion-builder' ),
					'description' => esc_attr__( 'Select the table style.', 'fusion-builder' ),
					'param_name'  => 'fusion_hero_type',
					'value'       => array(
						'1' => esc_attr__( 'Style 1', 'fusion-builder' ),
						'2' => esc_attr__( 'Style 2', 'fusion-builder' ),
					),
					'default'          => '1',
					'remove_from_atts' => true,
				),
				array(
					'type'        => 'select',
					'heading'     => esc_attr__( 'Number of Columns', 'fusion-builder' ),
					'description' => esc_attr__( 'Select how many columns to display.', 'fusion-
      builder' ),
					'param_name'  => 'fusion_hero_columns',
					'value'       => array(
						''  => esc_attr__( 'Select Columns', 'fusion-builder' ),
						'1' => esc_attr__( '1 Column', 'fusion-builder' ),
						'2' => esc_attr__( '2 Column', 'fusion-builder' ),
						'3' => esc_attr__( '3 Column', 'fusion-builder' ),
						'4' => esc_attr__( '4 Column', 'fusion-builder' ),
						'5' => esc_attr__( '5 Column', 'fusion-builder' ),
					),
					'default'          => '',
					'remove_from_atts' => true,
				),
				array(
					'type'        => 'tinymce',
					'heading'     => esc_attr__( 'Table', 'fusion-builder' ),
					'description' => esc_attr__( 'Table content will appear here.', 'fusion-builder' 
    ),
					'param_name'  => 'element_content',
					'value'       => '',
				),
			),
		)
	);
     }
     add_action( 'fusion_builder_before_init', 'fusion_element_hero' );


I was hoping that if extend the fusion element and inject assets that would be enough...

**Comment by mikka23** [comment]
The table element isn't a great example to work from because it works in a different way from other elements.  For the table element the options just trigger custom JS for creating table markup, which is then stored in element_content.  That isn't how regular elements work.  The actual code you posted will work for adding a new element though.

I have modified the code you posted for what I would say is a better example.  Easiest set-up is to do the following:

1.  Inside a child theme functions.php add:
```php
add_action( 'fusion_builder_shortcodes_init', 'load_my_element' );
function load_my_element() {
	include_once 'my-new-element.php';
}
```

This ensures the parent element class will be available and the various other FB functions.

2.  Add a new file to the child theme with the filename my-new-element.php.

3.  Inside that file add the code from - https://gist.github.com/mikka23/73c6fbcb9a0a5495dec28c942fa6760b

4.  Go to Fusion Builder > Settings and ensure Hero Component is checked.

5.  Create a new page, add a new element and select the hero component.


I copied the code you posted except made it more representative of a normal element.  So the render has changed to actually use the options.  The options allow you to select on the back-end a type, color, text and content.  Then the render uses this to create some simple markup (a div with a title and content and with the color used for either border color or background color depending on the type chosen).

**Comment by tyler-canton** [comment]
Also when I add the custom add-on this way and rename the shortcode to something like 'fusion-ugp' when embedding the code into the page the short code name actually renders and is not scraped from the html : [fusion_ugp] [/fusion_ugp]. How do I get rid of this?

**Comment by mikka23** [comment]
You mean, on front-end it doesn't render, instead it is just like shortcode format?

That should not be the case, unless the shortcode name is not named the same here - https://gist.github.com/mikka23/73c6fbcb9a0a5495dec28c942fa6760b#file-my-new-element-php-L30

Or this part of the code is not being called at all.

**Comment by tyler-canton** [comment]
Mikka I was very successful with the gist I apprecaite. I'm sending the starter element that I want to work with. My goal is to create a simple hero component for now and I want to utilize the image functionality to change the background image. I will later incorporate parallax into this. 

I'm starting with the fusion-image element, my key concerns are creating constant to access my child them assets:
-child-theme
  -custom-addons
    -- js
    -- css

Also I don't need the animation that in this element, and I need help taking it out:
 `fusion-image.php`
