### ISSUE TITLE
Range input type generates JS error with decimal increments

### ISSUE THREAD

**Issue by michelbayard** [Theme-Fusion/Fusion-Builder-Sample-Add-On#2]
When using the 'range' input control in the element's admin controls, using a 'step' value containing decimal places breaks the script execution, whereas whole numbers do not. 

The JavaScript error mentions "$step.countDecimals is not a function". It seems this function is called only when using floating point numbers in the 'step' setting, and the countDecimals function is not present in Fusion Builder.

**Comment by maximus80** [comment]
Currently you have to use full decimals, so instead of .5 you have to use 0.5 and it will work.
We will add a patch though for the next version, so that also the .5 notation can be used.

**Comment by maximus80** [comment]
This is done.
