### ISSUE TITLE
Child Theme Add On

### ISSUE THREAD

**Issue by tyler-canton** [Theme-Fusion/Fusion-Builder-Sample-Add-On#20]
Mikka I was very successful with the gist I apprecaite. I'm sending the starter element that I want to work with. My goal is to create a simple hero component for now and I want to utilize the image functionality to change the background image. I will later incorporate parallax into this.

I'm starting with the fusion-image element, my key concerns are creating constant to access my child them assets:
-child-theme
-custom-addons
-- js
-- css

Also I don't need the animation that in this element, and I need help taking it out:
fusion-image.php

**Comment by mikka23** [comment]
If you want to stick with a child theme you should be able to just use the two WP functions instead:
```php
get_stylesheet_directory_uri()
get_stylesheet_directory()
```

For animation it depends one exactly what you mean.  If you just don't want the animation options this can be removed from the option array.  If you don't want this used in the render you can remove all the references to the animation options, including the code which starts with
```php
$this->args['animation_type']
```

For the scripts, you also also remove from the add_scripts function.  However, that really isn't necessary. T he add_scripts function just tells the compiler that these scripts are necessary.  If that element is active (ie enabled in Fusion Builder > Settings) then the script will be loaded on the front-end.  It doesn't actually mean the element has to be on the page.  So even if the animation JS is removed it will still be getting enqueued in order for other elements to work properly.
