### ISSUE TITLE
Child Theme Enqueue Scripts

### ISSUE THREAD

**Issue by tyler-canton** [Theme-Fusion/Fusion-Builder-Sample-Add-On#21]
I'm using the child theme approach, will I still have access to functionality listed below:

Fusion_Dynamic_JS::enqueue_script( 'fusion-animations' );
Fusion_Dynamic_JS::enqueue_script( 'fusion-lightbox' );

**Comment by mikka23** [comment]
Yes, but if adding a custom script you will need to give the full details.  For example, for adding your own JS script for front-end use, it would require the following function added into the PHP class example I previously mentioned:

```php
		/**
		 * Sets the necessary scripts.
		 *
		 * @access public
		 * @since 1.1
		 * @return void
		 */
		public function add_scripts() {
			Fusion_Dynamic_JS::enqueue_script(
				'my-test-js-script',
				get_stylesheet_directory_uri() . '/js/my-test.js',
				get_stylesheet_directory() . '/js/my-test.js',
				array( 'jquery' ),
				'1',
				true
			);
		}
```
