### ISSUE TITLE
Question: Using Avada shortcode within addons

### ISSUE THREAD

**Issue by Zortrox** [Theme-Fusion/Fusion-Builder-Sample-Add-On#23]
In our addon we insert Avada's Popover element shortcode around a section of our generated HTML, then call "do_shortcode" on it.  This is so users can display a popover when they hover over a section of our custom element.  Would this be fine to do, or is there a better way to do this?

Thank you!

**Comment by maximus80** [comment]
Hello!

That is something that should be working, but we would need some more information or see the actual code snippet in order to provide an educated comment on the question. Is it possible for you to post us the code part in question here?

Thanks!

**Comment by mikka23** [comment]
@Zortrox If this is a question of permission, using the default shortcodes in that manner is fine.

**Comment by Zortrox** [comment]
@mikka23, that was exactly what I was asking for.  Thank you for the confirmation!  @maximus80, thank you for the help; it's working as expected!
