### ISSUE TITLE
Nested Fusion Builder Elements

### ISSUE THREAD

**Issue by Zortrox** [Theme-Fusion/Fusion-Builder-Sample-Add-On#24]
Hi,

I was wondering if it is permissible to create an element selector similar to the nested columns so we can let users easily create/add/edit fusion builder elements in our addons.  This way users don't have to insert shortcode into a tinymce container and become frustrated with editing there.

Thank you!

**Comment by maximus80** [comment]
Hey @Zortrox,

thanks for the question! Sounds like a good idea for UI reasons. As long as you use our API functions and do the additional genuine coding work yourself, that won't be a problem.

Thanks!
