### ISSUE TITLE
Official Methods to Show Fusion Elements Library

### ISSUE THREAD

**Issue by Zortrox** [Theme-Fusion/Fusion-Builder-Sample-Add-On#25]
Hello,

I was wondering if there was an official method/function to show the Fusion Elements Library (the popup that shows "Select Element".  Also, is there an official method to display the "+ Element" box that displays in Fusion Columns & Rows?  If we can find a way to mimic the "+ Element" functionality to bring up the element selector, select (and edit) an element, and display which element was selected in out add-on's field, that would be great!

Thank you!

**Comment by mikka23** [comment]
Hi Zotrox, can you provide a mockup/image example to demonstrate the situation? That will help understand what exactly to recommend.

Triggering the select element modal should not be a problem, but it depends on what exactly you need to happen when an element is then selected.

**Comment by Zortrox** [comment]
Thank you for the quick response!  The images below show the example field before an element is selected and after the element (Lightbox) is selected.  In the first image, the "+ Element" would theoretically function the same as in the default Fusion Builder (showing all the elements, nested columns, etc.).
![field-no-element](https://user-images.githubusercontent.com/10609756/42094480-88c97fb2-7b75-11e8-8447-914aa909feb4.jpg)
![field-with-element](https://user-images.githubusercontent.com/10609756/42094481-88dad212-7b75-11e8-8e6d-d9c3504b7a4e.jpg)

**Comment by mikka23** [comment]
In the above example, what would the saved value be?

**Comment by Zortrox** [comment]
Ah!  It would be either the shortcode for that selected element or possibly a base64-encoded shortcode if adding shortcode wouldn't be possible.  I'd be fine with either way.  For example:
`[custom_elem someAttribute="foo"][fusion_lightbox][/fusion_lightbox][/custom_elem]`
_or_
`[custom_elem base64Element="TWFuIGlzIGRpc3Rpb..."]`

**Comment by mikka23** [comment]
I see, let me give it a check.  Best idea is probably to utilize very similar to the tinymce editor and the shortcode generator button.  This would function in a very similar way, with just the addition of having to encode the value if saving as a param.

**Comment by mikka23** [comment]
Okay, so this should mostly be straight forward, there is just one extra slightly odd step you will need to add.

So the general approach I would recommend is to have a new option type.  In the template for that option have a button to trigger the element select and an input for storing the value (or two, one encoded and one not).  In my example I was just testing with a text input but you should be able to use a hidden input.  

Add a click event to the button along the lines of:
```js
this.$el.find( '.fusion-select-element' ).on( 'click', function() {
	var $testOption   = jQuery( this ).parents( '.fusion-test-option' ),
		$output       = $testOption.find( '.fusion-element-code' );

	if ( 'undefined' !== typeof window.tinyMCE ) {
		window.tinyMCE.activeEditor = false;
	}

	openShortcodeGenerator( $output );
} );
```

The idea of the above is that it checks for clicks on the button.  When it is click it sets the activeEditor to false, to prevent JS errors later.  Then it calls the function openShortcodeGenerator passing the input node as a parameter (where the shortcode content will be inserted).

You could then add an extra listener to the input if you want.  For example, to check when the value is changed and then encode the value to prevent it breaking the params (double quotes will break on save).

The relevant key parts from above are the function openShortcodeGenerator and the fact activeEditor needs set to false (unless the target input is tinymce instance of course).

**Comment by lukeabeck** [comment]
Closing out, let us know if you need anything else
