### ISSUE TITLE
It's Slow and Buggy

### ISSUE THREAD

**Issue by ghost** [Theme-Fusion/Fusion-Builder-Sample-Add-On#26]
I get this error when i want to update page:
`''[fusion_builder_container adm' (T_ENCAPSED_AND_WHITESPACE) in /home/iranfe/domains/crusherpartsequip.com/public_html/wp-content/uploads/fusion-builder-avada-pages/veterinarian.php on line 274`
anyone know how to correct that file?

**Comment by mikka23** [comment]
Hi @hasanparasteh 

Is this related to an add-on your are creating?  By the sounds of it, it is not.  This repository is specifically for the development of Fusion Builder add-ons, it is not a source of plugin support. For that please check the company website https://theme-fusion.com/
