### ISSUE TITLE
Custom Field Element for Fusion Builder

### ISSUE THREAD

**Issue by ghost** [Theme-Fusion/Fusion-Builder-Sample-Add-On#27]
Hi guys,

I have sent the new version of my plugin based on your feedback to the email where I sent the first version. Can you please have a look and see if you can put it on FB add-on page. 

I have already 6 sales but hope to have more with your help :)

**Comment by maximus80** [comment]
Thanks @waubau, we'll be looking into it and let you know :+1:

**Comment by slava-lu** [comment]
Hi @maximus80,  Any news?

**Comment by maximus80** [comment]
Hey guys,

sorry for the delay, we are quite busy at the moment. 
The changes do look good, only thing we saw is, that you missed 2 instances regarding fixing the text domain: https://prnt.sc/kfn8qv.
Would be good if you can update these soon.
We'll be going to upload your plugin info to our server in the meantime :-)

**Comment by slava-lu** [comment]
Hi, Sorry I missed that.  
I just fixed it and sent to Envato. You can see it under the same google drive link.

**Comment by maximus80** [comment]
Thanks for the quick update. Can you send the link please also to mark@theme-fusion.com?

**Comment by maximus80** [comment]
Your plugin is now available on our add-ons screen :-)

**Comment by slava-lu** [comment]
link sent. Thanks!
