### ISSUE TITLE
Trigger Scripts

### ISSUE THREAD

**Issue by alpezed** [Theme-Fusion/Fusion-Builder-Sample-Add-On#28]
Hi, Can you please help me to give an example how to run my script after modal is open when editing the custom element. Hope you can give me an idea about this. Thanks

**Comment by mikka23** [comment]
Hi,  can you explain the problem a bit more?  What specifically you are trying to accomplish.  We should then be able to recommend best way about going about that.

**Comment by alpezed** [comment]
Hi, Thanks for the quick response. I had created a custom element for user to search a stock image using ajax, the problem is, when i tried to edit my element the ajax doesn't load that's why the data doesn't retrieve but when i tried again to search on input field for photos the script is running. The only problem is the script is not working immediately when the modal is open. Sorry for my poor English. Hope it make sense.

**Comment by alpezed** [comment]
I tried to use this event **click .fusion-builder-settings** to run the script on modal popup when editing the element but the problem for this event is always run the script whenever you click on your page.

**Comment by mikka23** [comment]
Is this a custom option type then?  So you edit an element, then there is an image select field.  And from there you can search via ajax for stock image to use?

**Comment by alpezed** [comment]
On my custom element there is a text field to search a photo and the data coming from unsplash api, and for example when i search **mountain** on the field the photos show up and when i hit SAVE the data on search field which is the keyword **mountain** is saved, but the problem is when i open again the element the photos from that keyword **mountain** is not show up because the script is not triggered.

**Comment by alpezed** [comment]
What exactly i want is like the  **vc_add_shortcode_param('my_param', 'my_param_settings_field', get_template_directory_uri().'/vc_extend/flip.js');** the third parameter is the script run only when you open on that element.

**Comment by alpezed** [comment]
Hi, Here you can see the problem https://www.screencast.com/t/n2FUvUeVAMH

**Comment by mikka23** [comment]
It really depends on the overall set-up but I would recommend something like this.

1.  Create a new option type for yourself and use that for your param.
```php
add_filter( 'fusion_builder_fields', 'add_new_field' );
function add_new_field( $fields ) {
     $plugin_dir = plugin_dir_path( __FILE__ );
     $fields[] = array( 'param_type', $plugin_dir . 'templates/param_type.php' );
     return $fields;
}
```

That loads a new template file for a new param type called param_type.

Reference that in your option map for your element:
```php
array(
    type'        => 'param_type',
    'param_name'  => 'my_image_search',
    'heading'     => esc_attr__( 'My Image Search', 'my-builder' ),
    'description' => esc_attr__( 'Search for image.', 'my-builder' ),
    'value'       => '',
),
```

2.  Create the template with search input, saved value input and div for adding preview.
```php
<div class="my-image-search-option">
	<input
		type="hidden"
		name="{{ param.param_name }}"
		id="{{ param.param_name }}"
		class="my-saved-image-input"
		value="{{ option_value }}"
	/>

	<div class="my-image-results">

	</div>

	<input type="text" class="fusion-hide-from-atts" val="Search here..." id="my-image-searcher" name="my-image-searcher" />
</div>
<#
	jQuery( 'body' ).trigger( 'my-param-loaded', [ param.param_name ] );
#>
```

3.  Use that custom event as an init reference.  So JS ends up something like:
```js
jQuery( document ).ready( function() {

	// On init.
	jQuery( 'body' ).on( 'my-param-loaded', function( event, param_name ) {
		setTimeout( function(){
			var $option = jQuery( '[data-option-id="' + param_name + '"]' );

			if ( $option.length ) {
				// Run api fetching here.
				$option.find( '.my-image-results' ).append( '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Monasterio_Khor_Virap%2C_Armenia%2C_2016-10-01%2C_DD_25.jpg/1200px-Monasterio_Khor_Virap%2C_Armenia%2C_2016-10-01%2C_DD_25.jpg" />' );

				// Add listener to input search.
				$option.find( '#my-image-searcher' ).on( 'keypress change', function( event ) {
					console.log( jQuery( event.currentTarget ).val() );
				} );
			}
		}, 100 );
	} );
} );
```


There are plenty of other ways as well, but it depends on how the rest is set-up.  Also for future we should improve this by adding an event to the render method of element settings (that way no custom event or timeout would be necessary).

**Comment by alpezed** [comment]
Hi @mikka23 , Thank you for your answer, this is what i am looking for. I don't have an idea that it can put a custom event inside the template. i really appreciated your answer and it helps me a lot. Thanks!
