### ISSUE TITLE
fusion_builder_update_element

### ISSUE THREAD

**Issue by Zortrox** [Theme-Fusion/Fusion-Builder-Sample-Add-On#29]
Hi, we recently updated to Avada 5.7 and had an issue with our plugins displaying an error:
>argument #1 is not an array in /home/arcticlu/public_html/stage/wp-content/plugins/fusion-builder/inc/helpers.php

We fixed this by adding a conditional that the "fusion_builder_update_element" function will only run on the post.php and post-new.php files.  Is this the correct solution or does Avada 5.7 introduce a new way to use this function?
```PHP
global $pagenow;
if ( ( 'post.php' === $pagenow || 'post-new.php' === $pagenow ) ) {
    if ( function_exists( 'fusion_builder_update_element' ) ) {
        //lines that cause the above error
        fusion_builder_update_element( ... );
    }
}```

**Comment by yawalkar** [comment]
Yes, that is correct. The Fusion Builder elements will only be available on post edit screens, so the update element function also needs to run within the above conditions 👍

**Comment by MichaelWeb** [comment]
Hi there,

As a part of Fusion Builder performance improvement update the fusion_builder_map() function was limited to edit post, new post and Fusion Builder settings pages.
Your conditional is correct. If you would like to add settings page you can use the following conditional:

```
global $pagenow;
if ( ( is_admin() && isset( $pagenow ) && ( 'admin.php' === $pagenow && isset( $_GET['page'] ) && 'fusion-builder-settings' === $_GET['page'] ) || ( 'post.php' === $pagenow ) || ( 'post-new.php' === $pagenow ) ) ) {
```

**Comment by Zortrox** [comment]
Hi yawalkar and Michael, thank you for the quick feedback on this and additional information for the settings page!
