### ISSUE TITLE
My shortcode broke up the grid column

### ISSUE THREAD

**Issue by cdegourcy** [Theme-Fusion/Fusion-Builder-Sample-Add-On#3]
Thank for this awesome example of addon for FB!

I've built another one on my own, base on your work. It list some custom post type of my website. But I've met a problem, the column system was broke up. All columns was set with the `fusion-column-first` class, so each cell of my row was display under the previous one.

Used `get_posts()` instead `WP_Query` fixed the problem, do you know why ?

**Comment by maximus80** [comment]
This will depend on your setup. The columns can only be assigned the right classes, if the_content filter is run in your app, before content is output.

**Comment by yawalkar** [comment]
There's nothing to do with the sample addon code, so closing this for now.

**Comment by lukeabeck** [comment]
Currently we only have this one repo for FB add ons, which is for the sample add on, but if anyone has questions feel free to ask here.

Or we'd need to make a new repo for General FB API questions, etc
