### ISSUE TITLE
Add this code for another category also

### ISSUE THREAD

**Issue by jokew** [Theme-Fusion/Fusion-Builder-Sample-Add-On#30]
In that case i am afraid that is not really possible when using the default fusion blog shortcode.  Even if the placeholder could be overridden right now it does not check for a specific category.  So in your case you would not be able to alter the output just for a single category.

Instead, you would be better of filtering the entire shortcode output using a core WP filter.  For example:
```php
function empty_specific_category_blog( $output, $tag, $attr, $m ) {
	if ( empty( $output ) && 'fusion_blog' === $tag && isset( $attr['cat_slug'] ) && 'competition' === $attr['cat_slug'] ) {
		return 'No competitions to show.';
	}
	return $output;
}
add_filter( 'do_shortcode_tag', 'empty_specific_category_blog', 10, 4 );
```

You can add that to a child theme functions.php.  It will check if the output is empty (so this will only show if you are logged out, because placeholder is shown if logged in so output is not empty).  If the shortcode tag is fusion_blog and that the category selected is competition (assuming only a single category is selected)

_Originally posted by @mikka23 in https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/issues/18#issuecomment-364054672_

Hi @mikka23,

I found your solution for showing a message when there are no blogs available. Works perfectly for one category but I need to use this on 2 pages (both different category blogs).

I now have a page with category 'computing-promotions' where the code works. But I need another page with category 'printing-promotions' to show a message to (different one).

Could you help me please?

**Comment by mikka23** [comment]
If I understand correctly you just need to include both categories in the code in that case
```php
function empty_specific_category_blog( $output, $tag, $attr, $m ) {
	if ( empty( $output ) && 'fusion_blog' === $tag && isset( $attr['cat_slug'] ) ) {
		if ( 'printing-promotions' === $attr['cat_slug'] ) {
			return 'No printing promotions right now.';
		} else if ( 'computing-promotions' === $attr['cat_slug'] ) {
			return 'No computing promotions right now.';
		}
	}
	return $output;
}
add_filter( 'do_shortcode_tag', 'empty_specific_category_blog', 10, 4 );
```

**Comment by jokew** [comment]
Yes, that works perfectly! Thank you very much.
