### ISSUE TITLE
CSS for custom Fusion Element

### ISSUE THREAD

**Issue by nabrown** [Theme-Fusion/Fusion-Builder-Sample-Add-On#31]
In this add on, the following is used to add css file:
```
wp_enqueue_style( 'rotator-css', plugins_url( 'css/rotator.css', __FILE__ ) );
```
But in the documentation, it seems like `front_enqueue_css` is for this purpose:
```
'front_enqueue_css' => FUSION_BUILDER_PLUGIN_DIR . 'css/styles.css',
```

I tried adding the `front_enqueue_css` line to my `fusion_builder_map` array, but the CSS isn't getting picked up. What's the right way to do this?

**Comment by ilicfilip** [comment]
Hey @nabrown ,

Fusion Builder has been refactored recently and `front_enqueue_css` method doesn't work any more (we'll update documentation to match that).

You can of course use `wp_enqueue_style` and there is an example in our code sample here: https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/master/inc/class-sample-addon-fb.php#L76

**Comment by nabrown** [comment]
Thanks for the quick reply! I will do it with `wp_enqueue_style`, as you recommend.
