### ISSUE TITLE
Avada 6.0 Beta testing

### ISSUE THREAD

**Issue by slava-lu** [Theme-Fusion/Fusion-Builder-Sample-Add-On#32]
Hi, I am the add-on developer. I have received the email regarding  Avada 6.0 Beta testing. Can I have the access?

**Comment by maximus80** [comment]
Hello,

thanks for your interest to test Avada 6.0! Please sign-up for the beta list here: https://theme-fusion.com/beta/. Early access to the beta is only granted through an invitation from that list.

Thanks!
