### ISSUE TITLE
Trigger Event on Tab Change

### ISSUE THREAD

**Issue by alpezed** [Theme-Fusion/Fusion-Builder-Sample-Add-On#33]
Hi guys, 

Is there any event to trigger a script when user switch to another tab content? Here's the screenshot below:

![Screen Shot on Apr 17th at 10_17 AM](https://user-images.githubusercontent.com/4197193/56256279-94707800-60fa-11e9-9288-ce221e09cccb.png)

Thanks!

**Comment by maximus80** [comment]
Currently, there isn't, but we'll add one to our next release for your convenience. It will be called fusion-`switch-element-option-tabs`.
The next version is scheduled to be released within the next 2 weeks.

**Comment by alpezed** [comment]
Hi @maximus80, i really appreciate that. It's a big help for my plugin. Thank you so much!

**Comment by alpezed** [comment]
Hi, I'm just wondering how can i use the FusionPageBuilderEvents because i tried to use the event to trigger the script but it's not working, here's the code i tried to use:

$(document).on( 'fusion-switch-element-option-tabs', function ( event ) {
console.log('tab changed');
} );

**Comment by mikka23** [comment]
Hey, you should be able to listen like so:
```js
FusionPageBuilderEvents.on( 'fusion-switch-element-option-tabs', function() {
} );
```

**Comment by alpezed** [comment]
Hi, I did that already but it's not working.

**Comment by mikka23** [comment]
Which version of the plugin and are you wrapping that JS in anything?  For example if using jQuery you would need to wrap that within document ready.

**Comment by alpezed** [comment]
Oh I see, it's working now, i tried to wrap it inside the if statement:

if ( typeof FusionPageBuilderEvents !== 'undefined' ) {
  FusionPageBuilderEvents.on( 'fusion-switch-element-option-tabs', function() {
  } );
}

because it says "FusionPageBuilderEvents" is not defined, that's why it didn't work but now wrap it inside document ready is perfectly working. Thank you so much.
