### ISSUE TITLE
How to check the Fusion Builder is active

### ISSUE THREAD

**Issue by slava-lu** [Theme-Fusion/Fusion-Builder-Sample-Add-On#35]
Hi, I am a CPT plugin developer.  One of my clients requested that my plugin is activated only when the Fusion Builder is actually used.  
I can't use your action hook `fusion_builder_before_init` since my plugin requires that WordPress loads all the custom content before the plugin init, but `fusion_builder_before_init` fires before that, so I use different WordPress generic hook and need some way to check if I am on the page with the Fusion Builder. 

I need something similar to `is_admin()` but for the Fusion Builder.
Can you please advise on the best way to check it?

**Comment by mikka23** [comment]
Hi,

It depends on the overall problem really.  If you want to limit to just the post-new or edit pages then you can use:
```php
global $fusion_settings, $pagenow;

if ( 'post.php' === $pagenow || 'post-new.php' === $pagenow ) {
    // On editable page.
}
```

If you want to check the post type as well you can use the function for allowed post types (when FB will be active) and check if current post type is within there:
```php
FusionBuilder()::allowed_post_types()
```

A lot of that depends on timing though.

**Comment by slava-lu** [comment]
The solution above works fine for me. thanks.
