### ISSUE TITLE
Re-Render Parent When Child Changes

### ISSUE THREAD

**Issue by Zortrox** [Theme-Fusion/Fusion-Builder-Sample-Add-On#40]
Hi,

One of our addons uses the parent/child setup that needs to re-render the parent when a child element changes in the front-end builder.  I have tried calling the rendering functions from the extended `ParentElementView` class after the child is patched (like `patchView()` and `renderContent()`), but doing causes a loop of the child and parent elements to keep rendering each other (I'm guessing since `generateChildElements()` or something similar gets called again when the parent renders).

Is there a function that makes the parent element render again while not re-rendering the child elements?  Thank you in advance!

**Comment by maximus80** [comment]
It will depend a bit your use case. Can you elaborate on it a bit, please?
One candidate for a function to use would be `forceUpdateParent()` which is part of the base child element view.

**Comment by Zortrox** [comment]
Hi Maximus,

Thank you for the quick response!  I tried using that function as I didn't see it before, but that still wasn't working for me.  Our setup is a review element that takes the average star count of each child reviews plus the total number of reviews and adds it as a heading to the parent element.  It's using the template `<script>` elements and `fusion-child-element` class with the format:
```
<script id="tmpl-element-shortcode">
    <div class="parent">
        <h2>Total Reviews: {{{ TOTAL }}}</h2>
        <h2>Average Rating: {{{ AVERAGE }}}</h2>

        <div class="fusion-child-element">

            <!-- child elements are generated here -->

        </div>
    </div>
</script>
```

If possible, we just need a way to keep everything in the `fusion-child-element` in place and generate the rest of the template around it.  Alternatively, if we can just regenerate a specific `<div>` within the template, that would probably work as well.

**Comment by mikka23** [comment]
Hi @Zortrox 

I would probably just recommend a separate method for this and avoid re-render of the template.  So afterPatch on the child you could trigger a custom method on your parent view.  For example on child view:

```js
afterPatch: function() {
	var parentView = FusionPageBuilderViewManager.getView( this.model.get( 'parent' ) );
	parentView.updateTotalAverage();
},
```

Then in your parentView you can add something like so:

```js
updateTotalAverage: function() {
	var total,
		average;

	// Use this.model.children to calculate average score.
	total   = '20';
	average = '3.5';

	this.$el.find( 'h2.total-score' ).text( total );
	this.$el.find( 'h2.average-score' ).text( average );
},
```

**Comment by Zortrox** [comment]
Hi @mikka23,

That is a wonderful solution!  I was so stuck on getting it to re-render I didn't even think about just replacing the content directly.  Thank you so much!
