### ISSUE TITLE
How to use link selector object

### ISSUE THREAD

**Issue by alpezed** [Theme-Fusion/Fusion-Builder-Sample-Add-On#41]
Hi, I saw a file called link-selector-object.php which is i am trying to use, but i can't figure out how to use and make it work and there's no any elements that is using this field, can you give me please sample how to use this field or what paramater i need to use in order to make this work because for now when i tried to select a link then nothing is happening so i think there's a problem on my setup.

I want to use a link-selector-object becuase i want to get an array or object value intead of "link_selector" that return only a string of url.

Thanks.

**Comment by mikka23** [comment]
Hi Ed,

I am afraid that was never finished/released.  It was part of an earlier development cycle, but then was removed and hasn't been updated since.  We will have to re-check that to see if it is still valid at all or not.  The idea at the time was that it was the same as the current link selector, but as you say it would save multiple values rather than just the URL.

**Comment by mikka23** [comment]
Unfortunately that looks a fair bit off from being usable.  I assume this scenario for usage here is within a builder element?  If so what kind of parameters would you want in save?

**Comment by alpezed** [comment]
Hi mikka23, I see and i hope you can restore that field and update so i can use to my custom element, because the idea is like the elementor url control https://developers.elementor.com/elementor-controls/url-control/, and what i need are the url, nofollow and target field values.

**Comment by mikka23** [comment]
Ah, in that case the usage is different.  For something like that i would just suggest different inputs for each.  You can have one for url, one for target, one for no follow.  Then in your element just check the value for each.

The object link selector is different and refers to returning a post ID and information about a post and not a URL.

**Comment by alpezed** [comment]
Oh i see i understand, but i think using different input will not work on my shortcode, because for your information i have created a plugin that created a custom elements for each different builders like WP Bakery Page Builder, Elementor, Fusion Builder and other builders so those elements are connected for each Builders depending on what builder you are using and how the **link** input field works on other builder is using an array value like the **url control** from elementor, so i need a field input that has an array value, or maybe can you give me an idea if possible to create a custom param type that returns a array value, like creating my own custom param type for link selector but return an array "url, nofollow and target".
