### ISSUE TITLE
Use the Repeater options

### ISSUE THREAD

**Issue by SiKth** [Theme-Fusion/Fusion-Builder-Sample-Add-On#42]
There is an options field named repeater but it is not used by Fusion Builder as far as I can see. I am trying to use it but I can't get it to work unless I can find out what inputs it need.
Avada uses it for Custom Fonts and Social Media, but that doesn't get me anywhere either.

Anyone know how to use it?

**Comment by mikka23** [comment]
Hi @SiKth 

What is your use case?  We should have two different versions, so it will depend on the use-case for what I recommend.  I will also need to double check if that is fully integrated or not.  Originally the repeater was going to be used in an element, but then we ended up going in another direction.  So it may be that it is not fully integrated into the builder to use.

**Comment by SiKth** [comment]
I am creating custom settings for Containers, will be able to show and hide them depending on values that I enter in this settings area. I want the repeater field to be able to add as many textfields as you want. 
I get the repeater field to show with the button "Add more fields" and the fields get added, but the field does not contain anything. See image.

![Capture112233](https://user-images.githubusercontent.com/9527789/74823522-204cc500-5307-11ea-8f1c-c5c02b57e396.JPG)

**Comment by mikka23** [comment]
If its just a text field then I would recommend the sortable_text instead.  It is a lot simpler and we do use that in the plugin, so it will work.  You can also use the repeater field, but that was never complete or intended to be used inside the builder yet, so some of it will not work as expected (especially depends on the option types being used).

I have added an example for the repeater and the sortable_text option types to a new branch on this repo.  You can download/view it here - https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/tree/repeater.  It has a basic example of a repeater with text + textarea and an example of using sortable_text.

**Comment by SiKth** [comment]
Thanks for you assist!

Where is sortable_text used in the plugin? I will have a look at it, though i might need two text_fields that are linked to one another, like a Key and a Value.

The error i receive trying to use the repeater field is from this code:
```
		if ( 'raw_textarea' == param.type || 'repeater' == param.type ) {
			try {
				if ( FusionPageBuilderApp.base64Encode( FusionPageBuilderApp.base64Decode( option_value ) ) === option_value ) {
					option_value = FusionPageBuilderApp.base64Decode( option_value );
				}
			} catch(e) {
				console.warn( 'Something went wrong! Error triggered - ' + e );
			}
```
And it says: 
_**Something went wrong! Error triggered - TypeError: Cannot read property 'replace' of undefined**_

**Comment by mikka23** [comment]
sortable_text is used for animated title content (also pricing table but only in the live editor).

For the error, that will probably depend on what the content is.  Its also why there is the try/catch to prevent any decoding errors from breaking the rest of the editor. You were receiving that from the example branch I posted?

**Comment by SiKth** [comment]
Actually, it might work well with the sortable_text, I don't need to sort them but it works great.
I will try to lay the repeater field aside and try this solution, will get back with my progress.

Thanks a lot for you assist!

**Comment by SiKth** [comment]
So. I got really great help here the other day but now have i faced another issue. Let me know I should create a new issue, but it is more of a support question (even though this is not a support forum) :)

I am trying to add a new option to a container. Here is the code:

`add_filter( 'fusion_builder_fields', 'add_new_field' );
function add_new_field( $fields ) {
     $fields[] = array( 'param_type', plugin_dir_url( __FILE__ ) . 'param_type.php'); 
     return $fields;
}

function owe_filter_available_element( $fusion_builder_elements ) {
    if ( isset( $fusion_builder_elements['fusion_builder_container'] ) ) {
        $fusion_builder_elements['fusion_builder_container']['params'][] = array(
            'type'        => 'param_type',
            'heading'     =>  'PARAM TYPE',
            'description' => 'Description...', 
            'param_name'  => 'param_test,
            'value'       => array(
                "value1"     =>  "Value 1",
                "value2"     =>  "Value 2",
            ),
            'default'     => '',
        );
    }
}
add_filter( 'fusion_builder_all_elements', 'owe_filter_available_element' );`

This will add a new options section, but its empty. I have used this guide: https://theme-fusion.com/documentation/fusion-builder/filters/fusion_builder_fields/ And uses the code in the guide in the file param_type.php.

What am I missing here?
I really appreciate the help!

**Comment by SiKth** [comment]
Hi again,
I worked a lot with the branch you created, It works great. The thing is that I want to create this repeater setting field for a container, not a element. Is this possible?

**Comment by SiKth** [comment]
Hi again,
so the repeater field works great. Is it possible to get it to as a container option? 
I have iterally tried everything by now! (obviously not)

Thanks for the help so far!

**Comment by mikka23** [comment]
Hi,  you can add options with code something like:

```php
add_filter( 'fusion_builder_map', 'my_extra_container_options' );
function my_extra_container_options( $module ) {
	if ( isset( $module['shortcode'] ) && 'fusion_builder_container' === $module['shortcode'] ) {
		$module['params'][] = [
			'heading'     => esc_html__( 'Box Example', 'hello-world' ),
			'description' => esc_html__( 'Title and background color', 'hello-world' ),
			'param_name'  => 'repeater_example',
			'default'     => [],
			'type'        => 'repeater',
			'bind_title'  => 'box_title',
			'row_add'     => esc_html__( 'Add Box', 'hello-world' ),
			'row_title'   => esc_html__( 'Box', 'hello-world' ),
			'limit'       => 50,
			'fields'      => [
				'box_title'   => [
					'param_name' => 'box_title',
					'type'       => 'textfield',
					'heading'    => esc_html__( 'Box Title','hello-world' ),
					'value'      => '',
				],
				'box_description'   => [
					'param_name' => 'box_description',
					'type'       => 'textarea',
					'heading'    => esc_html__( 'Box Description','hello-world' ),
					'value'      => '',
				],
			],
		];
	}
	return $module;
}
```

Note, it will show up at the end of the first tab.  If you want you can also add a group param to set it to a specific tag `'group'       => esc_attr__( 'General', 'fusion-builder' ),`

**Comment by SiKth** [comment]
Thank you so much for this!
This was exactly what I was looking for.

**Comment by gpoole** [comment]
@mikka23 thanks for the repeater example, sorry to dig up an old issue but I think this is related. I've noticed that using `link_selector` fields doesn't seem to work with repeater. It shows the label and description, but not the actual selector widget.  I know you said the repeater is not finished and some things don't work, so I'm assuming that's why, but just in case: am I missing anything that would make it work?

**Comment by mikka23** [comment]
Depending on the use case, usually there is a better option than using the repeater setup.  So chances are you would be better using parent/child for example.  If you do need to add `link_selector` into repeater, you should be able to enable it with:

```php
add_filter( 'fusion_builder_repeater_fields', 'add_link_option' );
function add_link_option( $options ) {
    $options[] = 'link_selector';
    return $options;
}
```

But the actual link selection/saving may not work properly.

**Comment by gpoole** [comment]
Great, thanks for that. Also yes, thanks for the advice, I have used the parent/child sample for other elements and found it works well, my specific use case for this element is a bit weird so I felt it was simpler to use a repeater.

-------- Original Message --------

**Comment by chrisjcalderon** [comment]
Can tiny mce be used in a repeater?
