### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by NilsDannemann** [Theme-Fusion/Fusion-Builder-Sample-Add-On#43]
Hi Team,

I can't seem to get this to work and would have loved a bit more documentation.

My expectation was that I can simply...
a) download the repo
b) drop it into my **child-theme** folder
c) use the sample addon in the fusion builder
d) explore the code

However when I add the folder to my project I cant use the addon in fusion builder. 
Its also not listed in the settings.

Any help?

**Comment by mikka23** [comment]
It should still work, but a few things:
- Try the front-end branch version https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/tree/front-end
- Drop into wp-content/plugins rather than child theme
- Activate plugin in WordPress back-end
- Go to Fusion Builder > Settings and enabled the new element

**Comment by NilsDannemann** [comment]
Awesome, this seems to work. I'll have a look around.

Quick remark:
I'm getting an "unexpected output" error after activation. 

Is this just me? 
If not, and this is the "tutorial example" you might want to fix this. :-)

![image](https://user-images.githubusercontent.com/1572663/78526157-70a9b480-77d9-11ea-8ed7-45d70b6b7ed6.png)

**Comment by mikka23** [comment]
Thanks, I have updated that.

**Comment by NilsDannemann** [comment]
> Thanks, I have updated that.

Hmm... I'm afraid I'm still getting this error upon plugin activation. (with both approaches) 🤔 
Did you test the solution on your end? Not exactely sure where there could be an error on my end or how to fix this.

**Comment by mikka23** [comment]
Which branch are you using and what is the actual error?  Yes I tested the changed before committing.  Problem was just a left over line from the other branch.

**Comment by NilsDannemann** [comment]
Ah, my bad! 

This line was still present in my code:
`register_activation_hook( __FILE__, array( 'Sample_Addon_FB', 'activation' ) );	`

Sorry!
This can be closed again.
