### ISSUE TITLE
Scripts/Styles on frontend

### ISSUE THREAD

**Issue by alpezed** [Theme-Fusion/Fusion-Builder-Sample-Add-On#45]
Hi, I have a bunch of shortcodes and each shortcode template has scripts/styles enqueue but it's not working on frontend builder. example below:

```
function test( $atts, $content = null ) {
wp_enqueue_scripts( 'handle-script' );
....
}
add_shortcode('test', 'test');
```

The purpose of this is to load only specific assets on each selected shortcode. Thanks

**Comment by maximus80** [comment]
Hey, in the example files, you can see how scripts/styles need to be enqueued: https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/master/inc/class-sample-addon-fb.php#L76-L82.

**Comment by alpezed** [comment]
Hi, Thanks. but this this is not what i am looking for because i have a lot of scripts that load only for specific shortcode options so if i enqueue all the scripts using  `wp_enqueue_script ` hooks then a lot of uneccessary assets loaded on website, example i have a shortcode divider that has an options like array of `[ 'opt1', 'opt2', 'opt', etc... ]` then i only want to get the script from selected divider like wp_enqueue_script( 'opt1' ); if the `opt1 `is active or selected.

**Comment by aristath** [comment]
You could add the normal enqueue just for the live builder.
Loading scripts on-demand depending on the user's real-time selection could get messy. The easiest way to handle this would probably be to do what @maximus80 mentioned above, and wrap your enqueues in a condition like
`if ( function_exists( 'fusion_is_builder_frame' ) && function_exists( 'fusion_is_preview_frame' ) && ( fusion_is_builder_frame() || fusion_is_preview_frame() ) ) { .... }`
You can use your current implementation for the frontend, and the enqueue for the live builder.

**Comment by alpezed** [comment]
Thanks, but the scripts are not working after adding the action hook in the condition 

```
if ( function_exists( 'fusion_is_builder_frame' ) && function_exists( 'fusion_is_preview_frame' ) && ( fusion_is_builder_frame() || fusion_is_preview_frame() ) ) {
				add_action( 'wp_enqueue_scripts', array( $this, 'wp_enqueue_scripts' ) );
			}
```
it works without condition but the scripts are also loaded on frontend and i don't want to do that, i only need to load on front builder. any idea?

**Comment by aristath** [comment]
I was thinking you should add the check not to wrap the `add_action` call, but inside the method itself... So this:

```php
public function enqueue_scripts() {
	if ( function_exists( 'fusion_is_builder_frame' ) && function_exists( 'fusion_is_preview_frame' ) && ( fusion_is_builder_frame() || fusion_is_preview_frame() ) ) {
		// call wp_enqueue_script() here.
	}
}
```

**Comment by alpezed** [comment]
Hi, Thanks and it works inside method but i have another issue and there lot of scripts that are not working, a lot of **not defined** script error, here's one of the error in the console:
![2020-05-19 192308](https://user-images.githubusercontent.com/4197193/82320682-40734980-9a06-11ea-884b-e68256b784eb.png)
