### ISSUE TITLE
Adding the author avatar to the blog element

### ISSUE THREAD

**Issue by carolineleger** [Theme-Fusion/Fusion-Builder-Sample-Add-On#46]
Hi,

I'm using Avada theme and the Fusion Blog element as a grid. What I'm trying to do is get the author to be shown outside the metadata and add its avatar.

Something like that:
[https://i.ibb.co/gW8XDyC/Screenshot-2020-10-09-Intelematics-Website.png](url)

I've already a child theme setup, but not sure what to add in the functions.php (php is not really my strong suit!). Could you give me some direction?

Thanks!

Caroline

**Comment by maximus80** [comment]
Hello Caroline,

what you can do is, to use the `fusion_post_metadata_markup` filter in your child theme. In the function that uses the filter, you can use the WP native functions https://developer.wordpress.org/reference/functions/get_avatar/ and https://developer.wordpress.org/reference/functions/get_the_author/ to get author image and author name (link). The meta data options in the blog element, that you don't need can be disabled through the element options.
