### ISSUE TITLE
fatal error, fusion_builder_create_layout function not found

### ISSUE THREAD

**Issue by mjumayev** [Theme-Fusion/Fusion-Builder-Sample-Add-On#48]
in saved-templates/saved-elements.php  "fusion_builder_create_layout" function not found.
Is that function removed from fusion builder?
How to create libraries?
Thanks.

**Comment by maximus80** [comment]
Hello,

yes, this function does no longer exist. What exactly do you want to achieve? With some more info, we may be able to point you in the right direction.

Thanks

**Comment by mjumayev** [comment]
> Hello,
> 
> yes, this function does no longer exist. What exactly do you want to achieve? With some more info, we may be able to point you in the right direction.
> 
> Thanks

Thank you for response,

I thought using that function we can add predefined content to our elements like a library. Maybe user can select content from that library. If that functionality removed from Fusion Bulder, it is not important.

But actually I want to build addons to Fusion builder and I couldn't find documentation about how to build addons for Live front end editor. I can build for backend editor but in front editor not works, when changing value exits.
How can I create addons for live editor?
Thanks.

**Comment by maximus80** [comment]
For the front-end editor, you can find an example on the corresponding branch of this repo, which can serve you as a starting point https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/tree/front-end.

For the creation of prebuilt content on site, we suggest that you just create them using the builder and then save them as library items, so editors on your site can use them.
Delivering prebuilt content as part of an add-on would also be possible, but takes some digging into the code. As a starting point, you can take a look at the `add_new_library_element()` function in `fusion-builder/inc/class-fusion-builder-library.php`.

**Comment by mjumayev** [comment]
Thank you very much maximus80,
You saved my day, I didn't notice the branches.
Thank you.

**Comment by maximus80** [comment]
You are most welcome 😃
