### ISSUE TITLE
New Add on

### ISSUE THREAD

**Issue by slava-lu** [Theme-Fusion/Fusion-Builder-Sample-Add-On#49]
Hi,
I am the author of the couple of add-ons that are already displayed in the Avada Builder add-on area (Custom Post Types and Custom Fields)  and  I have just  created the new one for Custom Search. It does the similar thing as what the other add-ons do — it extends your Search Element be able to filter by any custom post types that the user has installed.

Here the link to the  Envato Page -  https://codecanyon.net/item/custom-search-element-for-avada-builder/31213422 
Could you please also add it to the  Avada Builder add-on section.

I have sent you the email on April 10th with the image.
Looking forward to hearing from you.

**Comment by mikka23** [comment]
Hi,

I am not seeing any emails about this.  Please send the plugin zip and imagery to our support@ email address and we can take a look and then add.

Thanks

**Comment by slava-lu** [comment]
Hi,
thanks for the quick  reply. Email is sent to support@.  Previously I sent it to info@.
