### ISSUE TITLE
Element Generator disappears

### ISSUE THREAD

**Issue by dloewen** [Theme-Fusion/Fusion-Builder-Sample-Add-On#5]
The Fusion Builder Element Generator button on the WYSIWYG toolbar disappears in some instances.

Steps to reproduce:

1. Edit a page with Fusion Builder
2. Add an element with nested items - for example the Testimonials element
3. Edit one of the items - notice the element generator button is missing
4. Exit the element's settings and create another element that has a WYSIWYG field, for example the Text element
5. Notice that element does have the element generator button. Now go back to editing one of the nested items in the Testimonials element. The element generator button appears.

**Comment by lukeabeck** [comment]
Hey @dloewen ... can you let us know which version of Avada you are using?

**Comment by dloewen** [comment]
Hi @lukeabeck, I'm using 5.0.5.

**Comment by lukeabeck** [comment]
Thanks @dloewen I've added it to our dev list to check out.

**Comment by MichaelWeb** [comment]
This one should be fixed. Reopen if needed.

**Comment by lukeabeck** [comment]
It'll be released in our next update 5.1

Thanks
