### ISSUE TITLE
Added multi-element shortcode with fusion_builder_map() is buggy in Avada Live

### ISSUE THREAD

**Issue by jbarkun** [Theme-Fusion/Fusion-Builder-Sample-Add-On#50]
Hello! I reached out to Avada Support and was instructed to post the issue I'm facing here instead.

 I followed [the documentation here](https://theme-fusion.com/documentation/avada/configure/add-new-multi-element-nested-shortcode-avada-builder/) on how to create a new multi-element shortcode for Avada Fusion Builder. I'm creating a custom slider element with [SwiperJS](https://swiperjs.com/) to cover some design cases the provided slider plugins don't work in, with the slider wrapper as the parent element and each slide as the children elements.

The added elements show up correctly in Avada Live, but when I try to change a child element's parameters, the 'Element Options' window goes blank (presumably when the parameters auto-save). To access it again, I have to click into a different element's options, then click back into the parent then child element, but the second I make any changes to the child element the Element Options will again disappear. What could be causing this?

Here's the mapping code, based off the code in the documentation link above:

```php
/**
 * Mapping to Fusion Bulder
 */
function rkd_shortcode_slider_map() {
    fusion_builder_map( array(
        'name'          => esc_attr__( 'Swiper Slider', 'fusion-builder' ),
        'shortcode'     => 'rkd_slider',
        'multi'         => 'multi_element_parent',
        'element_child' => 'rkd_slider_item',
        'params'        => array(
            array(
                'type'        => 'textfield',
                'heading'     => esc_attr__( 'Number of slides on desktop', 'fusion-builder' ),
                'param_name'  => 'slides_desktop',
                'value'       => '3',
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_attr__( 'Number of slides on mobile', 'fusion-builder' ),
                'param_name'  => 'slides_mobile',
                'value'       => '1',
            ),
            array(
                'type'        => 'radio_button_set',
                'heading'     => esc_attr__( 'Enable arrows', 'fusion-builder' ),
                'param_name'  => 'arrows',
                'value'       => array(
					'no'		=> esc_attr__( 'No', 'fusion-builder' ),	
					'yes'		=> esc_attr__( 'Yes', 'fusion-builder' ),				   
				),
            ),
            array(
                'type'        => '',
                'heading'     => esc_attr__( 'Extra Classes', 'fusion-builder' ),
                'description' => esc_attr__( 'Enter extra classes', 'fusion-builder' ),
                'param_name'  => 'el_classes',
                'value'       => '',
            ),
        ),
    ) );
}
add_action( 'fusion_builder_before_init', 'rkd_shortcode_slider_map' );


function rkd_shortcode_slider_item_map() {
    fusion_builder_map( array(
        'name'              => esc_attr__( 'Swiper Slide', 'fusion-builder' ),
        'description'       => esc_attr__( 'Individual slide for Swiper Slider', 'fusion-builder' ),
        'shortcode'         => 'rkd_slider_item',
        'hide_from_builder' => true,
        'params'            => array(
            array(
                'type'        => 'upload',
                'heading'     => esc_attr__( 'Slide Image', 'fusion-builder' ),
                'param_name'  => 'img',
                'value'       => '',
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_attr__( 'Image Alt tag', 'fusion-builder' ),
                'param_name'  => 'alt',
                'value'       => '',
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_attr__( 'Extra Classes', 'fusion-builder' ),
                'description' => esc_attr__( 'Enter extra classes', 'fusion-builder' ),
                'param_name'  => 'el_classes',
                'value'       => '',
            ),
        ),
    ) );
}
add_action( 'fusion_builder_before_init', 'rkd_shortcode_slider_item_map' );
```

Thank you for your help!

**Comment by mikka23** [comment]
If possible, please post the full zip of what you have so far.  I will check it out.

**Comment by jbarkun** [comment]
[rkd.zip](https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/files/6399510/rkd.zip)

Here's the child theme we're working in, there's not much in there yet besides the slider elements. 

Relevant files:
`functions.php`
`/js/sliders-init.js`
`/inc/shortcodes/shortcode-slider.php`
`style.css`

Thanks!

**Comment by mikka23** [comment]
[rkd.zip](https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/files/6400024/rkd.zip)

Here is a cleaned up version with the framework in place to work in the live editor.  Specifically I:
- Updated the shortcode PHP file to extend our element class, it makes things easier and copies the structure we use.
- Added some todo comments for asset enqueueing in that file
- Added live editor templates and views for the parent and child elements.  You can find them in inc/live-editor.  Essentially the view is just a JS version of what you do in the PHP render.  This way the element can update live on change rather than ajax (which was the source of the other problem, parent + child doesn't work in the live editor without views/templates).  The view creates the variables which are passed into the template (if you check the example files it should be fairly clear).

To make it useful you will want to ensure CSS and JS for slider init are added properly.  Note, the developer docs on the site are very out of date.  The readme here is slightly more up to date https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On#readme. Also I would suggest checking our own elements, for example the countersbox or other simpler parent/child ones.

**Comment by jbarkun** [comment]
Wow thank you, that helped a lot! The issues with the live editor aren't happening with the new files. I think I'm following what was done and how to properly integrate new elements moving forward, thank you for the detailed response and taking the time to point me in the right direction.
