### ISSUE TITLE
Trying to add some JS that runs in the element options

### ISSUE THREAD

**Issue by steveadamsfixedit** [Theme-Fusion/Fusion-Builder-Sample-Add-On#51]
I'm trying to create a drop down menu that uses AJAX in the backend of a custom element. Using the Avada Builder, and adding my custom element to the page I created using this sample element as a template...I'm hoping to offer a "choose file" drop down that automatically populates the options from my database table of assets. 
  Where should I put this javascript so it runs IN the element editing options modal?

**Comment by mikka23** [comment]
Hi @steveadamsfixedit  

More information would be required here.  Right now I am really struggling to understand what exactly you are trying to accomplish.

For triggering JS when the element editing modal is opened, you should be able to use this event - **fusion-settings-modal-open**.  You can find another older issues that seems somewhat similar here - https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/issues/28.

**Comment by steveadamsfixedit** [comment]
@mikka23 I would like to add some event listeners to a textfield I've tried adding callbacks as described in the [README](https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/front-end/README.md) but adding the `callbacks` described there doesn't cause any functions to fire, doesn't yield any errors in the console, and doesn't fire off any AJAX requests.

I've also tried to attach event listeners which would run when Fusion Builder renders the data entry form for my element. The window.load event fires but the fusion-element-render-my_short_code event does not:
```js
jQuery( window ).on( 'load', function( $ ) {
   // i see this in the console
   console.log('window load adding specific listener');
   jQuery( window ).on( 'load fusion-element-render-my_short_code', function( $, cid ) {
   // this code never runs
   console.log('YO YO ITS FIRING, cid=' + cid);
   });
});
```
Could you provide a JS example for the `fusion-settings-modal-open` event you suggested? It might be helpful if there were a canonical/authoritative list of the events that fire with some examples about how to capture them?

**Comment by sneakyimp** [comment]
It would certainly be helpful to have a list of the events that Fusion Builder fires and examples of how to add event listeners for these events.Googling 'Fusion Builder Events' yields a bunch of links to the Events Calendar. [Searching your documentation](https://theme-fusion.com/?s=events&post_type=documentation) certainly doesn't yield any list of events.

**Comment by mikka23** [comment]
@steveadamsfixedit I would need to see the actual code to understand what you are trying to achieve.

@sneakyimp right now there just isn't the demand for add-ons to warrant such extensive documentation.  Right now the best information is here https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/front-end/README.md and figured out by checking our own elements.

**Comment by sneakyimp** [comment]
@mikka23 Just a list of the events and a brief description would be of great interest to me. Also, I originally tried the callbacks in that README file and could not get either element-specific or ajax callbacks to work.

Per the [element-specific option](https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On#adding-callbacks-to-an-element-or-specific-option), I tried adding a callback to my array in fusion_builder_map:

```
'name'          => esc_attr__( 'MycoLiveStream', 'fusion-builder' ),
'shortcode'     => 'fusion_mycompany_livestream',
'admin_enqueue_js'=> '/wp-content/plugins/Fusion-Builder-Myco-Mux-Live-Stream/js/admin.js',
'icon'          => 'fusiona-vimeo2', // FIXME change this icon
'preview'       => MYCO_ADDON_PLUGIN_DIR . 'inc/templates/fusion-livestream-preview.php',
'preview_id'    => 'fusion-builder-block-module-livestream-preview-template',
'help_url'      => 'https://example.com',
// attempted callback here
'callback' => [
	'function' => 'fusion_ajax',
	'action' => 'myco_action',
	'ajax'     => true, 
],
'params'        => [] // blah blah same as before
```

This did not produce any PHP errors or errors in the JS console, but neither did it create any AJAX requests to the server.

I also tried adding a callback directly to the textfield input but it never seemed to call any function when I changed input values.
```
'params'        => [
	[
		'type'          => 'textfield',
		'heading'       => esc_attr__( 'Wordpress Video ID', 'fusion-builder' ),
		'description'   => esc_attr__( 'This will be a Wordpress Media ID, e.g. 3194', 'fusion-builder' ),
		'param_name'    => 'myco_video_id',
		'value'         => '',
		// callback fn, does nothing
		'callback'    => [
		'function'  => 'myfunc', // also tried fusion_preview, whatever that is.
		'args'          => [
			'selector' => '.fusion-fullwidth',
			'property' => 'background-color',
			]
		],
	]
	// etc, same parameters as before
]
```
this also did not create any errors or AJAX requests. I did check the JS generated for the page and I can clearly see these values included in the `fusionAllElements` value defined in the page's JS.
