### ISSUE TITLE
my-param-loaded event fires, but my input elements don't yet exist in the page

### ISSUE THREAD

**Issue by sneakyimp** [Theme-Fusion/Fusion-Builder-Sample-Add-On#52]
Following the instructions [here](https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/issues/28#issuecomment-421309587), I have managed to get my custom element type started. It appears in the page. I have some admin JS enqueued which also seems to work, but some how the event I'm triggering is not able to locate my input elements when I use `document.getElementById()`

```js
// suggested here: https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/issues/28
jQuery( document ).ready( function() {
	// add event listener which will fire as each mycompany_video input is loaded
	jQuery( 'body' ).on( 'mycompany-video-option-loaded', function( event, param_name ) {
		// this fires
		console.log('mycompany-video-option-loaded fired, param_name=' + param_name);


		// let's try adding simple autocomplete
		let ac_id = param_name + '_input';
		console.log('CCE: ac_id=' + ac_id); // outputs mycompany_video_id_input
		ac_el = document.getElementById(ac_id);

		// THIS IS ALWAYS NULL
		// somehow the HTML elements do not yet exist in the page
		console.log(ac_el);

		// SADLY I am unable to do anything with my inputs because I cannot locate them

	} );
} );
```

I have edited a fields/mycompany_video.php file that looks like this:
```php
<div class="mycompany-video-option">
        <input
                type="hidden"
                name="{{ param.param_name }}"
                id="{{ param.param_name }}"
                class="mycompany-video-option-hidden-input"
                value="{{ option_value }}"
        />
        <input type="text" class="fusion-hide-from-atts" value="Use this to select video" id="{{ param.param_name }}_input" name="{{ param.param_name }}_input" />
        <div id="{{ param.param_name }}-results" class="mycompany-video-results">

        </div>

</div>
<#
        // this event is firing, and *should* fire after the HTML above is rendered, but i cannot locate my HTML elements
        // in the document
        jQuery( 'body' ).trigger( 'mycompany-video-option-loaded', [ param.param_name ] );
#>
```
Am I doing something wrong? Is it impossible to refer to my HTML elements in this function I'm triggering?

**Comment by mikka23** [comment]
You are better off using the **fusion-settings-modal-open event** instead. If you use the approach like you have there you will need to add a timeout.  Notice the timeout on the example here. https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/issues/28#issuecomment-421309587

 **fusion-settings-modal-open event** is a jQuery event you can listen for, it triggers when the element settings modal is opened and rendered.  So you can listen for that then just search for options of the name or type you want to target.

**Comment by sneakyimp** [comment]
>You are better off using the fusion-settings-modal-open event instead. If you use the approach like you have there you will need to add a timeout. Notice the timeout on the example here. #28 (comment)

Thank you for the suggestion. I had considered a timeout, but the page already seems pretty sluggish to load -- E.g., I see the default editor until Avada editor eventually loads and modifies the UI.

Per your suggestion, I tried this in my admin.js:
```js
jQuery( document ).ready( function() {
        console.log('ready fired');

        jQuery('body').on('fusion-settings-modal-open', function(event) {
                console.log('fusion-settings-modal-open FIRED');
        });
} );
```
I see the 'ready fired' in the console but the *fusion-settings-modal-open* event never fires.  I'd greatly appreciate any JS you could suggest to capture the **fusion-settings-modal-open** event.

**Comment by sneakyimp** [comment]
@mikka23 I still haven't managed to capture the fusion-settings-modal-open event. Any thoughts?

**Comment by mikka23** [comment]
More or less what you already posted, but the event listeners are different:
```js
// Back-end listener.  Ensure FusionPageBuilderEvents type of first.
FusionPageBuilderEvents.on( 'fusion-settings-modal-open', function(event) { } );

// Live editor listener.  Ensure FusionEvents type of first.
FusionEvents.on( 'fusion-settings-modal-open', function(event) { } );
```
