### ISSUE TITLE
requiring textfield data entry in custom element modal

### ISSUE THREAD

**Issue by steveadamsfixedit** [Theme-Fusion/Fusion-Builder-Sample-Add-On#53]
I have constructed a custom element that generates a custom short tag and I want to add in a required field with minor validation.

1) How can you specify that a text field is required and has a minimum required length? We currently have this PHP code in our call to fusion_builder_map:

[
'type'        => 'textfield',
'heading'     => esc_attr__( 'Video Title', 'fusion-builder' ),
'description' => esc_attr__( 'This is the Video Event Title', 'fusion-builder' ),
'param_name'  => 'mycompany_video_title',
'value'       => '',
],

This correctly displays a text input on the dynamically generated form -- we need to make sure this input is REQUIRED and has a minimum length of 3 characters.

2) How do you intercept the form submission such that you can prevent the form from being submitted? While it might be possible to add another event listener function to the SAVE button by selecting its class of "fusion-builder-modal-save" and adding an event listener, but this would not prevent this button from submitting the form. Can you provide some example JS about how to detect a click of the SAVE button and prevent the form from being submitted if some condition is not met?

**Comment by maximus80** [comment]
Hello,

currently there is no way to inject custom properties, like `required` or char length into the builder options. So, any checks you want to run would have to be done through JS code you create.
Alternatively you can create your own new option type. An outline regarding the how to can be found here: https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/issues/28#issuecomment-421309587.

regarding the saving of options through clicking the save button, only thing that would work is, that you disable the button through the above JS code you create, until cour criteria is met. So, on modal open, you'd need to check value of your input, and also on any change of that input. If criteria are met, enable the button, else disable it.
