### ISSUE TITLE
Isolation of Fusion builder elements (shortcodes)

### ISSUE THREAD

**Issue by slava-lu** [Theme-Fusion/Fusion-Builder-Sample-Add-On#54]
Hi,
I am the author of this [add-on ](https://codecanyon.net/item/custom-post-types-and-taxonomies-for-fusion-builder/15572585)

The elements I create are based on the existing elements and enhance their functionality mainly with additional features related to the custom post types and taxonomies. The way I do it, I take the existing shortcode like `Portfolio`, rename the class e.g. to `FusionSC_Portfolio_CPT` and the function that builds the configuration option screen to e.g. `fusion_element_portfolio_cpt`  Then I add some of my code to this  new element. This approached worked fine in Avada 6. At some point in Avada 7 my shortcode resulted in some warning for the original shortcode  even though I did not touch the original shortcode:
`Warning: Trying to access array offset on value of type null in /home/t/talentboru/ts/public_html/wp-content/plugins/fusion-core/shortcodes/fusion-portfolio.php on line 1565
`

This was OK since they are not visible without the Debug mode turned on, but still was annoying for some of my customers. Unfortunately since Avada 7.9. along with this warning I now have the problem with shortcode display where regardless of my settings I see the full text of  the element and than the extract. [The example](http://www.talentschool.ru/1_test/) 
The issue and the warnings  disappear if I disable the original `Portfolio `shortcode (element) in the FB settings.
Since 7.9 I also started receiving some complains about my other shortcode based on the Button element. 

So the issue/question is: How do I now properly isolate my shortcode from your shortcode. It looks like renaming the Classes and functions outside the Class are not enough.  
Can you please advise?

Regards,
Slava.

**Comment by maximus80** [comment]
Hello!

It does sound like you are not setting the `$args` member variable of the element class. Which would lead to the warning and also to the fact that you get the full content.

The warning suggests that `$args` is null here: https://i.imgur.com/5K0juRu.png. Make sure to set it correctly in the `render()` function and it should start to work.

**Comment by slava-lu** [comment]
Thanks,  that helped! I will close the issue.
