### ISSUE TITLE
feedback on incorrect key value logic from a add on creator

### ISSUE THREAD

**Issue by lukeabeck** [Theme-Fusion/Fusion-Builder-Sample-Add-On#6]
Here is there reply, please post an answer asap so I can let him know either way (our fault and being fixed, or the reasoning behind it)

------------------------------------------------------------------

_Just wanted to share some feedback. For some reason you have inverted key-value logic for shortcode values. See the screenshot below.  You have an array with keys like "heading" and with value of some text. But for values array you have made a text as a key and the text name as a value. That is so  illogical. And you mixed the key-value logic in the shortcode array. No one uses the free text as an array key as the key is used for iterating the array!  I now have so many bugs in my plugin for Avada 5 because of it. Still fixing it._ 

_I do not know why you have done it but if you will ever re-do it please make the array key what should be the key._

------------------------------------------------------------------

**Comment by mikka23** [comment]
Yeah this has been brought up before and can't say I disagree.  Although im not sure how that can cause bugs in a plugin.

**Comment by maximus80** [comment]
This is not a bug, but it is something that has been weird from the beginning. Not easy to change now though. A conversion would be needed for this.

**Comment by ghost** [comment]
Hi guys, 

This was the issue from me. The problems appear when you try to create more complicated structures with FB. For my plugin I need a list of custom post types, taxonomies and terms.  They may have the same nice name that I want to show to a user but  taxonomy for post is different from taxonomy for other custom post type as far as my plugin is concerned. in version 4 I easily created a key that was unique. Now my key is what a user sees in the select box so it is no longer nice and short. 

I recognize that you can't just change it but you should keep in mind that it will make building extensions to FB more difficult.

**Comment by lukeabeck** [comment]
> I recognize that you can't just change it but you should keep in mind that it will make building extensions to FB more difficult.

This is certainly something we do not want. Yet a conversion is even worse. 

@Theme-Fusion/developers will check into this more once we get through our current 5.1 update.

**Comment by yawalkar** [comment]
@lukeabeck, @maximus80  We can do this without conversion.

**Comment by maximus80** [comment]
Well it is not a "user install" based conversion, but a conversion inside our element and also template files to get this done.

This will men that current add-ons will have to adjust their settings too to reflect that, which is bad. But better to do it now than when there are 100 add-ons.

**Comment by lukeabeck** [comment]
> But better to do it now than when there are 100 add-ons.

Agreed, being discussed in our team and we'll update this item once everything is decided.

**Comment by yawalkar** [comment]
The changes to the array logic are done. We are good with the arrays now.

**Comment by ghost** [comment]
Thanks for that. 
Is it now in Avada master branch for me to modify my plugin? How much time do I have before you release it?

**Comment by lukeabeck** [comment]
It's in our private repo for the next update.

5.1 will be released sometime in February.

Also, we will have beta testing, which I believe you are already part of, if not I'll add your username and you will be notified when we start it.

**Comment by lukeabeck** [comment]
Yep your username is already in the beta repo as a collaborator, so when we tart beta testing you'll be able to check it out.

Thanks
