### ISSUE TITLE
multi_element_parent with groups

### ISSUE THREAD

**Issue by biffly** [Theme-Fusion/Fusion-Builder-Sample-Add-On#7]
Hi, I'm developing an addon for fusion builder. This has elements of the type "multi_element_parent" but I want to place in the parent groups apparently the standard visualization does not contemplate it, could they help me ?. Thank you.

**Comment by yawalkar** [comment]
Can you please explaing your query with more details? What you are trying to achieve and the issues you are facing? So we might be able to help you.

**Comment by biffly** [comment]
My english is very bad, I'm sorry

 - I have an addon based on the example. But in the general options I have many and I want to group them. 
My problem is that when I do the visualization does not seem to support it, the elements go down.

### I have it now
![image](https://cloud.githubusercontent.com/assets/8367673/22248757/e921c320-e21e-11e6-83b5-03b0763df165.png)

### When I group the options on the right
![image](https://cloud.githubusercontent.com/assets/8367673/22248781/00092bfa-e21f-11e6-84f7-4446f1c8acd5.png)

**Comment by yawalkar** [comment]
This is fixed in the development version for now. So this will be good in next release.

However, to get the things working for you just now, please add the following css to the `wp-content/plugins/fusion-builder/css/fusion-builder.css `

```
.fusion-builder-main-settings-advanced .fusion-tabs {
    float: right;
    width: 67%;
    padding-top: 1.5em;
    margin-top: 1.5em;
    margin-bottom: 0;
}

.fusion-builder-main-settings-advanced .fusion-tabs .fusion-builder-module-settings {
    width: 100%;
}
```

**Comment by biffly** [comment]
Gracias, i added:
``` CSS
.fusion-tabs-menu li{float:right;}
```

**Comment by yawalkar** [comment]
That will override all the tabs.
