### ISSUE TITLE
tinymce in multi_element_parent

### ISSUE THREAD

**Issue by biffly** [Theme-Fusion/Fusion-Builder-Sample-Add-On#8]
Hi, is it possible to place a tinymce element in the general configuration of a multi element?

my code
```php
fusion_builder_map(
		array(
			'name'          				=> __( 'MGS Form', 'fusion-builder' ),
			'multi'         				=> 'multi_element_parent',
			'shortcode'     				=> 'fusion_mgs_forms',
			'element_child' 				=> 'fusion_mgs_form_elemento',
			'icon'          				=> 'fa fa-code-fork',
			'preview'       				=> MGS_FORMS_PLUGIN_DIR . 'js/preview/preview.php',
			'preview_id'					=> 'fusion-builder-block-module-mgs-forms-addon-preview-template',
			'params'        => array(
				array(
					'type'        => 'tinymce',
					'heading'     => '',
					'description' => '',
					'param_name'  => 'element_content',
					'value'       => '[fusion_mgs_form_elemento]Formulario[/fusion_mgs_form_elemento]',
				),
				/*	ID	*/
				array(
					'type'        	=> 'textfield',
					'heading'     	=> 'Nombre',
					'description' 	=> __( 'Nombre del formulario', 'mgs-forms' ),
					'param_name'  	=> 'name',
					'value'       	=> '',
					'placeholder' 	=> true,
				),
				
				array(
					'type'        => 'tinymce',
					'heading'     => __( 'Texto', 'fusion-builder' ),
					'description' => __( 'Texto', 'fusion-builder' ),
					'param_name'  => 'mensaje',
					'value'       => '',
				),
			)	
		)
	)
```
The problem I see is that it does not display

**Comment by maximus80** [comment]
This is possible in general.

I assume that is only part of the code you use, as it is not complete. But the field definition for the tinymce foeld is correct.

Just make sure that you don't use the same param name,
`'param_name'  => 'element_content',`
below that field again.

**Comment by lukeabeck** [comment]
Closing this out, please reply back if needed.

**Comment by thiru-ikomet** [comment]
Hi anybody, please help me.
i'm facing this issue, but i have only one tinymce in fusion_builder_map() function. yet i couldn't see it in my browser, when i inspect in my browser, it's div had affected by "display:none" property and also this contains only <textarea> in the hidden div,,, good answers will be appreciated..

**Comment by yawalkar** [comment]
Hi,

Can you please confirm that you don't have setup the dependency for the param? Aosl, to debug the issue, would you mind providing your code here, so that we can check?

Thank you,
Nitin

**Comment by thiru-ikomet** [comment]
fusion_builder_map(
		array(
			'name'          => esc_attr__( 'Circle Image Thumbnail', 'fusion-builder' ),
			'shortcode'     => 'fusion_thumbnails',
			'multi'         => 'multi_element_parent',
			'element_child' => 'fusion_thumbnail',
			'icon'          => 'fa fa-thumbs-up',
			'preview'       => IMAGETHUMBNAIL_ADDON_PLUGIN_DIR . 'js/preview/sample-addon-preview.php',
			'preview_id'    => 'fusion-builder-block-module-sample-addon-preview-template',
			// 'allow_generator'   => true,
			'params'        => array(
				array(
					'type'        => 'tinymce',
					'heading'     => __( 'Content', 'fusion-builder' ),
					'description' => __( 'Enter some content for this Thumbnail.', 'fusion-builder' ),
					'param_name'  => 'element_content',
					'value'       => '[fusion_thumbnail title="Quote 1"]Your Content Goes Here[/fusion_thumbnail]',
				),
				array(
					'type'        => 'tinymce',
					'heading'     => __( 'Texto', 'fusion-builder' ),
					'description' => __( 'Texto', 'fusion-builder' ),
					'param_name'  => 'mensaje',
					'value'       => '',
				),
				array(
					'type'          => 'colorpicker',
					'heading'    	=> __( 'Background Color', 'fusion-builder' ),
					'param_name'    => 'bg_color',
					'value'         => '#47a3da',
					'description'   => __( 'Set the background color.', 'fusion-builder' ),
				),
				array(
					'type'          => 'textfield',
					'heading'    	=> __( 'Title', 'fusion-builder' ),
					'param_name'    => 'title',
					'value'         => 'Enter here',
					'placeholder'	=> true,
					'description'   => __( 'Enter your thumbnails Heading.', 'fusion-builder' ),
				),
				array(
					'type'          => 'colorpicker',
					'heading'    	=> __( 'Quote Title Color', 'fusion-builder' ),
					'param_name'    => 'color_quote_title',
					'value'         => '#47a3da',
					'description'   => __( 'Set the quote title color.', 'fusion-builder' ),
				),
			),
		)
	);

**Comment by thiru-ikomet** [comment]
this is my code, i need to add tinymce in parent, but it doesn't shows

**Comment by yawalkar** [comment]
You have 2 instances of tinymce param. Which is why it doesn't work as expected. Please remove the one for the `'param_name' => 'mensaje',` and the first one will be displayed. If you need it in both parent and child items, you can simply use the first one in both params array.

**Comment by thiru-ikomet** [comment]
No, in begin, i added only one tinymce array with this parameter 'param_name'  => 'element_content',
it doesn't work.
after i readout this github only, i added another one with 'param_name' => 'mensaje'

it doesn't work even i put only one tinymce

**Comment by thiru-ikomet** [comment]
please help me to overcome this obstacles..

**Comment by thiru-ikomet** [comment]
i have spoiled 2 hours today, am really frustrated for this issue.!

**Comment by yawalkar** [comment]
It looks like you missed to add the code for your child element. Which is why it doesn't work and throws error in the console - https://cl.ly/352N453o3J39

Please follow the sample add-on code and check now the child - parent shortcodes work. If you remove these two lines in your code, the settings window loads fine - https://cl.ly/3c0I2q0F0C1q

```
'multi' => 'multi_element_parent',
'element_child' => 'fusion_thumbnail',
```

**Comment by thiru-ikomet** [comment]
But i added my child correctly here,

fusion_builder_map(
		array(
			'name'              => esc_attr__( 'Thumbnail', 'fusion-builder' ),
			'shortcode'         => 'fusion_thumbnail',
			'hide_from_builder' => true,
			'allow_generator'   => true,
			'params'            => array(
				array(
					'heading'     => __( 'Image', 'fusion-builder' ),
					'description' => __( 'Upload the image you would like to use for this thumbnail.', 'fusion-builder' ),
					'value'       => '',
					'type'        => 'upload',
					'param_name'  => 'image',
				),
				array(
					'type'        => 'textfield',
					'heading'     => esc_attr__( 'Thumbnail Title', 'fusion-builder' ),
					'description' => esc_attr__( 'Title of the thumbnail.', 'fusion-builder' ),
					'param_name'  => 'title',
					'value'       => 'Enter Here',
					'placeholder' => true,
				),
				array(
					'type'        => 'textfield',
					'heading'     => esc_attr__( 'Thumbnail Link', 'fusion-builder' ),
					'description' => esc_attr__( 'Url of the thumbnail.', 'fusion-builder' ),
					'param_name'  => 'url',
					'value'       => 'Enter Here',
					'placeholder' => true,
				),
			),
		)

this is my child..

**Comment by thiru-ikomet** [comment]
even i don't have any error in my console.

**Comment by yawalkar** [comment]
Hi,

If you want to use the textarea in the parent, this is not possible, as the tinymce output is set as the content for the parent shortcode, so if you want to add the tinymce to the child element, you can simply move the second tinymce from your code to the child element map. Like below - 

```
fusion_builder_map(
	array(
		'name' => esc_attr__( 'Thumbnail', 'fusion-builder' ),
		'shortcode' => 'fusion_thumbnail',
		'hide_from_builder' => true,
		'allow_generator' => true,
		'params' => array(
			array(
				'type' => 'tinymce',
				'heading' => __( 'Texto', 'fusion-builder' ),
				'description' => __( 'Texto', 'fusion-builder' ),
				'param_name' => 'mensaje',
				'value' => '',
			),
			array(
				'heading' => __( 'Image', 'fusion-builder' ),
				'description' => __( 'Upload the image you would like to use for this thumbnail.', 'fusion-builder' ),
				'value' => '',
				'type' => 'upload',
				'param_name' => 'image',
			),
			array(
				'type' => 'textfield',
				'heading' => esc_attr( 'Thumbnail Title', 'fusion-builder' ),
				'description' => esc_attr( 'Title of the thumbnail.', 'fusion-builder' ),
				'param_name' => 'title',
				'value' => 'Enter Here',
				'placeholder' => true,
			),
			array(
				'type' => 'textfield',
				'heading' => esc_attr__( 'Thumbnail Link', 'fusion-builder' ),
				'description' => esc_attr__( 'Url of the thumbnail.', 'fusion-builder' ),
				'param_name' => 'url',
				'value' => 'Enter Here',
				'placeholder' => true,
			),
		),
	)
);
```

I hope this will help. Please remove the second instance of the tinymce from your parent named `mensaje`.

Let me know if that helps.

Thanks,
Nitin

**Comment by thiru-ikomet** [comment]
This answer is great but it will help to every children,, but my requirement is, I have a block, that contains number of childrens(thumbnails) and a paragraph(for parent) and a title(for parent). so i have to capsule all 1.childrens 2. Title 3.Paragraph. into a addon(plugin). So only i need the tinymce in parent.

i have a big doubt only is, why do we cant add tinymce in parent,, because this element is also like other elts like, inputfield,carousel.....etc, we could add other elements into parent, but why do we cant only the tinymce?

Really thank you very much to spend your golden time for me.

**Comment by yawalkar** [comment]
> i have a big doubt only is, why do we cant add tinymce in parent

Because the tinymce is used to generate html content, and the generated content can only be inserted as shortcode content and not as shortcode attribute. If you have a parent - child element, using tinymce in parent will remove the shortcode you will put as child in your parent shortcode. If you want the tinymce generated output to be set as shortcode attribute, please note that the shortcode attribute contains value in double quote pair like `background="red"` if you put the html inside it, it will possibly break the shortcode if the html contains double quote.

I hope this will help you understand the use of tinymce.

Thank you,
Nitin

**Comment by thiru-ikomet** [comment]
Ohh okay. Now I can understand. But I need the requirement, if any ways are possible please update me

Thank you so much bro.
Thiru

**Comment by yawalkar** [comment]
Instead of tinymce, you can use textarea in parent.

Hope that helps.

**Comment by thiru-ikomet** [comment]
But i need tinymce, this only easily can convert text to html, so only, Okay, for now i'm going to use textarea.

Thank you bro.

**Comment by biffly** [comment]
It is impossible, you should create your own visualization for it. Unfortunately the documentation is terrible.

**Comment by thiru-ikomet** [comment]
Yes Biffly, in document, they called tinymce editor, in the parent function, i follow the documentation yet this is not working..
Its okay am using inputfield for now.

Thank you,
Thiru

**Comment by thiru-ikomet** [comment]
Hi,
I use Avada theme, I need to add extra options in theme options. Any possibility in there?

Thanks,
Thiru

**Comment by biffly** [comment]
> Yes Biffly, in document, they called tinymce editor, in the parent function, i follow the documentation yet this is not working..

Esto es por la forma en que se crea el shortcode, es imposible.

> I use Avada theme, I need to add extra options in theme options. Any possibility in there?

Good question, unfortunately I do not know and support avada is not good, almost never respond.

**Comment by maximus80** [comment]
Hey guys,

the Fusion Builder API documentation is still work in progress, and we are revisiting and adding articles for/to it. Currently it does contain the most important information about available fields, hooks and also a sample add-on, so that developers can create their add-ons. Obviously the docs are not perfect yet, and also not everything is possible yet within the API, so sometimes developers will have to go the extra mile, but that simply is what a developer would expect anyways.

Apart from that let me clearly state, that the docs are by no means "terrible", and also that the theme support is definitely one of the best in the industry. We do respond to each and every ticket in a timely manner.
That is quite obvious, as even here, so apart from the official ticket system you get replies within a short period of time. Alone the fact, that we do have a public sample add-on repo on git shows, that ThemeFusion cares a lot and tries to help.

Lastly, let me please remind you, @biffly, that while we are happy to help where we can, we do expect users and developers to be polite and to stick to facts (and saying that support "almost never respond"s clearly is wrong).

Thanks guys!

**Comment by yawalkar** [comment]
Hi @thiru-ikomet,

Regarding adding the options in Avada Theme Options is relatively easy as we have already provided an example in this sample addon. 

Please check this file, and how we have added the options in Theme Options - https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/master/options/sample-options.php

You just need to require the above file on `fusion_builder_shortcodes_init` action like below - 
https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/blob/8cdb0e982d3b39934756b035c1b9b81e651de572/fusion-builder-sample-add-on.php#L296-L309

This is already implemented in the sample add-on. Please take a look at the code and you'll find there are few other examples that will help you to extend Fusion Builder API for your add-on.

I hope this will help. If you still have any questions, please feel free to contact us.

Thank you,
Nitin

**Comment by thiru-ikomet** [comment]
Thank you so much Nitin,

You are always helping me.
Thanks,

**Comment by sergiolara** [comment]
Good evening it is possible to color a page builder or a nested column inside a custom addon for fusion builder what would the call be thanks

**Comment by sergiolara** [comment]
No color insertar the Page builder
